### ISSUE TITLE
Problems with the player hanging on 0:00 or 0:01 and not going to next song

### ISSUE THREAD

**Issue by Edza** [ChilloutMusica/cms#7] opened 2016-04-16 17:52 UTC
This happens after hours of playing. F5 doesnt help. Hard reload + Clear cache doesnt help. Clearing "Local storage" doesnt help. Shutting down chrome fixes it.

I cant be the only one!

Here is my quick and dirty fix. I do not expect you to implement it, but polish it and you are gonna have a killer feature people will want because your plugin will not have this dubtrack bug:

```
setInterval(function() {
    if(($(".sec").text() == "01" || $(".sec").text() == "00")
    && $(".min").text() == "00"
    ) {
        console.log("timer set");
    setTimeout(function() {
        console.log("timer entry");
        if(($(".sec").text() == "01" || $(".sec").text() == "00")
            && $(".min").text() == "00") 
        {
            $(".icon-reload.refresh-el.show").click();
            console.log("refreshed");
        }
    }, 1000)
    }
    console.log("big tick");
}, 2000);
```

I have this as injected javascript using cjs and no problems since.

Best of luck,
- edza

**Comment by PossiblyKris** [comment] 2016-04-16 22:09
Thanks for the concern - as per our talk, I'm gonna go ahead and close this, as it seems to be an isolated incident, possibly caused by extensions or other circumstantial interference. We'll consider looking into this if it becomes a widespread issue and Dubtrack doesn't fix it.

**Closed by PossiblyKris** 2016-04-16 22:09 UTC
